name: Rust Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      - name: Check if project compiles
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      
      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          
      - name: Run the program
        run: ./target/release/rust_system_info